"""Restore earnings_events and historical_prices from sector archives to production.

The Tier 3 cleanup pass deleted these tables' historical data from production after 90 days.
This script copies them back from the 19 sector archives using INSERT OR IGNORE
(unique constraints prevent duplicates, existing production data is never overwritten).

Safe to run multiple times — fully idempotent.

Usage:
    python data/health/restore_from_archives.py              # Full restoration
    python data/health/restore_from_archives.py --dry-run    # Preview without writing
    python data/health/restore_from_archives.py --table earnings_events  # Single table
"""

import argparse
import glob
import os
import sqlite3
import sys
import time

# Paths relative to project root
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, '..', '..'))
ARCHIVE_DIR = os.path.join(PROJECT_ROOT, 'data', 'sector_archive')
PRODUCTION_DB = os.path.join(PROJECT_ROOT, 'data', 'datalake.db')

TABLES_TO_RESTORE = ['earnings_events', 'historical_prices']

# Columns to exclude from INSERT (auto-generated by production)
EXCLUDE_COLUMNS = {
    'earnings_events': ['event_id'],  # AUTOINCREMENT — let production assign its own IDs
    'historical_prices': [],
}

BATCH_SIZE = 5000


def get_column_names(conn, table_name):
    """Get column names from a table via PRAGMA table_info."""
    cursor = conn.execute(f"PRAGMA table_info({table_name})")
    return [row[1] for row in cursor.fetchall()]


def get_insert_columns(prod_conn, archive_conn, table_name):
    """Find columns common to both production and archive, minus excluded columns.

    Returns list of column names to use in SELECT and INSERT.
    """
    prod_cols = set(get_column_names(prod_conn, table_name))
    archive_cols = set(get_column_names(archive_conn, table_name))
    exclude = set(EXCLUDE_COLUMNS.get(table_name, []))

    # Intersection minus excluded, preserving a stable order (sorted for reproducibility)
    common = sorted((prod_cols & archive_cols) - exclude)
    return common


def restore_table(prod_conn, archive_path, table_name, dry_run=False):
    """Copy one table from one archive into production.

    Args:
        prod_conn: Open connection to production datalake.db
        archive_path: Full path to sector archive .db file
        table_name: Table to restore
        dry_run: If True, count rows but don't insert

    Returns:
        tuple: (rows_found, rows_inserted)
    """
    archive_name = os.path.basename(archive_path)

    try:
        # Open normally (not URI mode) — Windows backslash paths break file: URI scheme.
        # Script never writes to archives (SELECT only), so read-only enforcement not needed.
        archive_conn = sqlite3.connect(archive_path)
    except sqlite3.OperationalError as e:
        print(f"    {table_name}: ERROR opening archive — {e}")
        return 0, 0

    try:
        # Check if table exists in archive
        cursor = archive_conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
            (table_name,)
        )
        if not cursor.fetchone():
            print(f"    {table_name}: not found in archive, skipping")
            return 0, 0

        # Get common columns
        columns = get_insert_columns(prod_conn, archive_conn, table_name)
        if not columns:
            print(f"    {table_name}: no common columns, skipping")
            return 0, 0

        columns_str = ', '.join(columns)
        placeholders = ', '.join(['?'] * len(columns))

        # Count total rows in archive for this table
        count_cursor = archive_conn.execute(f"SELECT COUNT(*) FROM {table_name}")
        total_rows = count_cursor.fetchone()[0]

        if total_rows == 0:
            return 0, 0

        if dry_run:
            return total_rows, 0

        # Read in batches and insert
        select_sql = f"SELECT {columns_str} FROM {table_name}"
        read_cursor = archive_conn.cursor()
        read_cursor.execute(select_sql)

        insert_sql = f"INSERT OR IGNORE INTO {table_name} ({columns_str}) VALUES ({placeholders})"
        rows_found = 0
        rows_inserted = 0

        while True:
            batch = read_cursor.fetchmany(BATCH_SIZE)
            if not batch:
                break

            rows_found += len(batch)
            before_changes = prod_conn.total_changes
            prod_conn.executemany(insert_sql, batch)
            rows_inserted += prod_conn.total_changes - before_changes

            # Progress for large tables (every 25K rows)
            if rows_found % 25000 == 0 and total_rows > 25000:
                pct = rows_found / total_rows * 100
                print(f"      ... {rows_found:,}/{total_rows:,} ({pct:.0f}%)")

        return rows_found, rows_inserted

    finally:
        archive_conn.close()


def main():
    parser = argparse.ArgumentParser(description='Restore archived data to production')
    parser.add_argument('--dry-run', action='store_true', help='Preview without writing')
    parser.add_argument('--table', choices=TABLES_TO_RESTORE, help='Restore single table only')
    args = parser.parse_args()

    tables = [args.table] if args.table else TABLES_TO_RESTORE
    mode_label = "DRY RUN" if args.dry_run else "LIVE"

    # Find all sector archives
    archive_pattern = os.path.join(ARCHIVE_DIR, '*.db')
    archives = sorted(glob.glob(archive_pattern))

    if not archives:
        print(f"No archives found in {ARCHIVE_DIR}")
        sys.exit(1)

    # Header
    print(f"\n{'=' * 60}")
    print("  RESTORE ARCHIVED DATA TO PRODUCTION")
    print(f"{'=' * 60}")
    print(f"  Tables:   {', '.join(tables)}")
    print(f"  Archives: {len(archives)} sector databases")
    print(f"  Mode:     {mode_label}" + (" (use --dry-run to preview)" if not args.dry_run else ""))
    print(f"  Target:   {PRODUCTION_DB}")
    print(f"{'=' * 60}\n")

    # Open production connection
    if not args.dry_run:
        prod_conn = sqlite3.connect(PRODUCTION_DB)
        prod_conn.execute("PRAGMA busy_timeout = 30000")
        prod_conn.execute("PRAGMA journal_mode = WAL")
        prod_conn.execute("PRAGMA synchronous = NORMAL")
        prod_conn.execute("PRAGMA cache_size = -256000")  # 256 MB
    else:
        # Read-only for schema inspection in dry-run mode
        # Convert backslashes to forward slashes for SQLite URI scheme on Windows
        uri_path = PRODUCTION_DB.replace('\\', '/')
        prod_conn = sqlite3.connect(f"file:{uri_path}?mode=ro", uri=True)

    start_time = time.time()

    # Track totals per table
    totals = {t: {'found': 0, 'inserted': 0} for t in tables}

    try:
        for i, archive_path in enumerate(archives, 1):
            archive_name = os.path.basename(archive_path)
            print(f"[{i}/{len(archives)}] {archive_name}")

            for table_name in tables:
                found, inserted = restore_table(prod_conn, archive_path, table_name, args.dry_run)

                totals[table_name]['found'] += found
                totals[table_name]['inserted'] += inserted

                if found == 0:
                    print(f"    {table_name}: empty")
                elif args.dry_run:
                    print(f"    {table_name}: {found:,} rows available")
                else:
                    skipped = found - inserted
                    print(f"    {table_name}: {found:,} found -> {inserted:,} inserted, {skipped:,} already existed")

            # Commit after each archive
            if not args.dry_run:
                prod_conn.commit()

    except KeyboardInterrupt:
        print("\n\nInterrupted! Committing work done so far...")
        if not args.dry_run:
            prod_conn.commit()
    finally:
        prod_conn.close()

    elapsed = time.time() - start_time
    minutes = int(elapsed // 60)
    seconds = int(elapsed % 60)

    # Summary
    print(f"\n{'=' * 60}")
    if args.dry_run:
        print(f"  DRY RUN COMPLETE ({minutes}m {seconds}s)")
    else:
        print(f"  RESTORATION COMPLETE ({minutes}m {seconds}s)")
    print(f"{'=' * 60}")

    for table_name in tables:
        t = totals[table_name]
        if args.dry_run:
            print(f"  {table_name}: {t['found']:,} rows available in archives")
        else:
            skipped = t['found'] - t['inserted']
            print(f"  {table_name}: {t['found']:,} found -> {t['inserted']:,} inserted ({skipped:,} already existed)")

    print()


if __name__ == '__main__':
    main()
