#!/usr/bin/env python3
"""
Email Notifier - SMTP Email Wrapper
====================================
Simple wrapper for sending email notifications using existing config.json settings.

Uses Gmail SMTP configuration from config.json's email_reports section.

Usage:
    from tools.email_notifier import send_email

    send_email(
        subject="Error Alert",
        body="Critical error detected in system",
        config=config_dict  # Optional, auto-loads if not provided
    )

Author: Ben (with Claude)
Date: 2025-10-15
"""

import logging
import smtplib
import json
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

# Configure UTF-8 encoding for Windows compatibility (MANDATORY)
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')


def load_config(config_path=None):
    """Load configuration from JSON file

    Args:
        config_path: Optional path to config.json

    Returns:
        dict: Configuration dictionary
    """
    if config_path is None:
        # Default to project root config.json
        project_root = Path(__file__).parent.parent
        config_path = project_root / 'config.json'

    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        raise Exception("Failed to load config: {}".format(e))


def send_email(subject, body, config=None, config_path=None):
    """Send email notification using Gmail SMTP

    Args:
        subject: Email subject line
        body: Email body (plain text)
        config: Optional config dict (auto-loads from config.json if not provided)
        config_path: Optional path to config.json

    Returns:
        bool: True if email sent successfully, False otherwise
    """
    # Load config if not provided
    if config is None:
        try:
            config = load_config(config_path)
        except Exception as e:
            print("ERROR: Could not load config: {}".format(e))
            return False

    # Extract email settings
    email_config = config.get('email_reports', {})

    if not email_config.get('enabled', False):
        print("Email notifications disabled in config.json")
        return False

    smtp_server = email_config.get('smtp_server')
    smtp_port = email_config.get('smtp_port')
    username = email_config.get('username')
    password = email_config.get('password')
    recipient = email_config.get('default_recipient')

    # Validate required fields
    if not all([smtp_server, smtp_port, username, password, recipient]):
        print("ERROR: Incomplete email configuration in config.json")
        return False

    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = username
        msg['To'] = recipient
        msg['Subject'] = subject

        # Attach body
        msg.attach(MIMEText(body, 'plain'))

        # Connect to SMTP server and send
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(username, password)
        server.send_message(msg)
        server.quit()

        logging.debug("Email sent successfully to {}".format(recipient))
        return True

    except Exception as e:
        print("ERROR: Failed to send email: {}".format(e))
        return False


def send_error_alert(report_text, config=None):
    """Send error alert email with log analysis report

    Convenience function for log analyzer integration.

    Args:
        report_text: Full log analysis report text
        config: Optional config dict

    Returns:
        bool: True if email sent successfully
    """
    subject = "⚠️ Critical Errors Detected - Options Scanner"

    # Create body with summary at top
    body_lines = []
    body_lines.append("Critical errors were detected in the options scanner system logs.")
    body_lines.append("")
    body_lines.append("This is an automated alert generated by the log analyzer.")
    body_lines.append("Please review the full analysis report below:")
    body_lines.append("")
    body_lines.append("=" * 70)
    body_lines.append("")
    body_lines.append(report_text)

    body = "\n".join(body_lines)

    return send_email(subject, body, config=config)


if __name__ == "__main__":
    # Simple test mode
    import sys

    if len(sys.argv) < 3:
        print("Usage: python tools/email_notifier.py <subject> <body>")
        print("Example: python tools/email_notifier.py 'Test Alert' 'This is a test message'")
        sys.exit(1)

    subject = sys.argv[1]
    body = sys.argv[2]

    success = send_email(subject, body)
    sys.exit(0 if success else 1)
